version: '3.6'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi_gpt
    container_name: fastapi_gpt
    command: fastapi run app/main.py --port 8080
    volumes:
      - './app:/code/app'
    environment:
      OPENAI_API_KEY: ${KEY:-}
      TEST: ${TEST:-}
    ports:
      - "8080:8080"
    networks:
      - app_network


networks:
  app_network:
    driver: bridge
