version: '3'
services:
  web:
    build:
      context: .
      dockerfile: DockerFile
      args:
        foo: bar
    image: nginx:latest
    container_name: web_server
    command: command...
    volumes:
    - ./foo:bar
    environment:
      foo: bar
    ports:
    - 80:80
    networks:
    - app_network
    depends_on:
    - service 0
  web2:
    build:
      context: .
      dockerfile: DockerFile
      args:
        foo: bar
    image: nginx:latest
    container_name: web_server
    command: command...
    volumes:
    - ./foo:bar
    environment:
      foo: bar
    ports:
    - 80:80
    networks:
    - app_network
    depends_on:
    - service 0
networks:
  app_network:
    driver: bridge
